name: Publish

on: 
  workflow_dispatch:
  repository_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          persist-credentials: false

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
        
      - name: Install dependencies
        run: bun deps
   
      - name: Compile code
        run: bun compile

      - name: Publish
        run: bun publish:patch
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        

