name: Publish Major Version

on: 
  workflow_dispatch:
  repository_dispatch:
  
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          persist-credentials: false

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
        
      - name: Install dependencies
        run: bun deps
   
      - name: Compile code
        run: bun compile

      - name: Publish
        run: bun pub:major
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        

